server:
  port: 9297

spring:
  application:
      name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NayarBEP3/brbank.develop-config.git
          clone-on-start: true
          default-label: master